
# Application Configuration
spring.application.name=Cricriser

# MongoDB Connection
spring.data.mongodb.uri=mongodb+srv://<username>:<password>@<cluster-host>/<database>?retryWrites=true&w=majority
spring.data.mongodb.database=<database>

# Gmail SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=<your-email@gmail.com>
spring.mail.password=<your-email-password>
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Optional file for secrets
spring.config.import=optional:file:./application-secret.properties

